mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
        path('polls/', include('polls.urls')),
        path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
# urlpatterns coordinate coordinate views with paths requests
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/delete/', views.DeleteQuestionView.as_view(), name='delete'),
    path('newQuestion/', views.NewQuestionView.as_view(), name='newQuestion'),
    path('addNewQuestion/', views.add_new_question, name='addNewQuestion'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_total_votes(self):
        total_votes = 0
        for choice in self.choice_set.all():
            total_votes += choice.votes
        return total_votes


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
# Create your views here.
import datetime
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Choice, Question
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.views.generic.edit import CreateView
from django.utils import timezone


# This view lists all the available polls / questions.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:6]


# This view shows the specific poll's polling station with voting options
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


# This view shows the specific poll's current voting results
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# This view shows the delete confirmation when a poll is being deleted
class DeleteQuestionView(DeleteView):
    model = Question
    template_name = 'polls/deleteQuestion.html'
    success_url = '/polls/'
    # def get_total_votes(self):
    #     total_votes = 0
    #     for choice in self.choice_set.all:
    #         total_votes += choice.votes
    #     return total_votes


# This view shows a new question / poll creation form
class NewQuestionView(CreateView):
    model = Question
    template_name = 'polls/newQuestion.html'
    fields = ['question_text']
    # success_url = '/polls/'
    # def get_total_votes(self):
    #     total_votes = 0
    #     for choice in self.choice_set.all:
    #         total_votes += choice.votes
    #     return total_votes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context["range"] = range(3)
        return context


# This function handles a new question and its choices being posted to database.
def add_new_question(request):
    # extract all form fields data
    new_question_text = request.POST['question_text']
    pub_date = request.POST.get('pub_date')
    pub_time = request.POST.get('pub_time')
    pub_date_time = pub_date + " " + pub_time

    choice_0 = request.POST.getlist('choice')[0]
    choice_1 = request.POST.getlist('choice')[1]
    choice_2 = request.POST.getlist('choice')[2]
    choice_3 = request.POST.getlist('choice')[3]

    date_time_obj = datetime.datetime.strptime(pub_date_time, '%Y-%m-%d %H:%M:%S')

    # persist new question / poll into database, along with choices
    new_question = Question(question_text=new_question_text, pub_date=date_time_obj)
    new_question.save()
    if choice_0:
        new_question.choice_set.create(choice_text=choice_0, votes=0)
    if choice_1:
        new_question.choice_set.create(choice_text=choice_1, votes=0)
    if choice_2:
        new_question.choice_set.create(choice_text=choice_2, votes=0)
    if choice_3:
        new_question.choice_set.create(choice_text=choice_3, votes=0)

    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list}
    # return render(request, 'polls/index.html', context)
    return HttpResponseRedirect(reverse('polls:index'))


# This function handles updating database when a vote is submitted for a poll/question.
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href='/static/polls/style.css?{% now "U" %}'>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Polls App</title>
  </head>
  <body>
      <nav class="navbar navBar">
        <span class="navbar-brand mb-0 h1">Polls App</span>
      </nav>
      {% block content %}
      {% endblock %}
  </body>
</html>

mysite/polls/templates/polls/deleteQuestion.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="containerParent">
        <div class="deletingContainer">
            <h3 class="detailTitle">Delete Question Confirmation</h3>
            <form method="post">
                {% csrf_token %}
                <h3>Are you sure you want to delete this question?<h3>
                    <h4>Question:</h4>
                    <p>{{ question }}?</p>
                    <h4>Total Votes</h4>
                <p>{{ question.get_total_votes}} votes.</p>
                 <button type="submit" class="btn btn-success voteButton">Confirm Delete!</button>
            </form>
             <a class="btn btn-primary btn-lg active pollsButton" href="{% url 'polls:index'%}">Go Back to Polls</a>
        </div>
    </div>
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class = "detailsContainer">
        <div class="detailsFormVoteContainer">
            <h2 class="detailTitle">Poll Station</h2>
            <h4><b>Question: </b>{{ question.question_text }}</h4>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                    <div class="form-check choice">
                        <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success voteButton">VOTE!</button>
            </form>
            <a class="btn btn-primary btn-lg active pollsButton" href="{% url 'polls:index'%}">Go Back to Polls</a>
        </div>
    </div>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="pollsContainer">
        <table class="table table-striped pollsTable">
             <thead>
                    <tr>
                        <h4 class = "listTitle">List of available Polls:</h4>
                    </tr>
                    <tr class="rowTable">
                        <th scope="col">#</th>
                        <th scope="col">Available Polls</th>
                        <th scope="col"></th>
                    </tr>
             </thead>
             <tbody>
                {% for question in latest_question_list %}
                    <tr>
                        <th scope="row">{{question.id}}</th>
                        <td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
                        <td class="deleteCol"><a class="btn btn-success deleteLink" href="{% url 'polls:results' question.id %}">View Results</a><a class="btn btn-secondary deleteLink" href="{% url 'polls:delete' question.id %}">Delete</a></td>
                    </tr>
               {% endfor %}
             </tbody>
        </table>
        <a class="btn btn-primary btn-lg active" href="{% url 'polls:newQuestion'%}">Create New Question</a>
    </div>
{% endblock %}

mysite/polls/templates/polls/newQuestion.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="newQuestionContainer">
    <form action="{% url 'polls:addNewQuestion'%}" method="post">{% csrf_token %}
        <h4 class="newQuestionFormTitle"><b>Enter new question details below:</b></h4>
        {{ form.as_p }}
        <label>Please select published (date, time):</label>
        <input type="date" name="pub_date" value="2017-06-01">
        <input type="time" name="pub_time" step="3" value="00:00:00">
        <br>
        <label class="newformLabel"><b>Please enter (upto 4) choices for this question:</b></label>
        <br>
        <label>Choice (required):</label>
        <input required type="text" name="choice">
        <br>
        {% for i in range %}
          <div>
            <label>Choice (optional):</label>
            <input type="text" name="choice">
          </div>
        {% endfor %}
        <button type="submit" class="btn btn-success saveButton">Save!</button>
    </form>
    <a class="btn btn-primary btn-lg active pollsButton" href="{% url 'polls:index'%}">Go Back to Polls</a>
</div>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}

    <div class="pollsContainer">
        <table class="table pollsTable">
             <thead>
                    <tr>
                        <h4 class = "listTitle">Poll Results</h4>
                    </tr>
                    <tr class="titleRow">
                        <h5 class="titleRow"><b>Question:</b> {{question.question_text}}</h5>
                    </tr>
                    <tr class="rowTable choiceRow">
                        <th scope="col">Choice</th>
                        <th class="votesCol" scope="col">Votes</th>
                    </tr>
             </thead>
             <tbody>
               {% for choice in question.choice_set.all %}
                    <tr class="choiceRow">
                        <td >{{ choice.choice_text }}</td>
                        <td class="votesCol"> {{ choice.votes }}</td>
                    </tr>
              {% endfor %}
               <tr class="totalsRow">
                   <td><b>TOTAL</b></td>
                   <td class="votesCol" ><b>{{ question.get_total_votes}}</b></td>
               </tr>
             </tbody>
        </table>
        <a class="btn btn-lg active btn-success" href="{% url 'polls:detail' question.id %}">Vote again?</a>
        <a class="btn btn-primary btn-lg active" href="{% url 'polls:index'%}">Go Back to Polls</a>
    </div>
{% endblock %}